---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 26364.
--- DateTime: 2025/4/27 17:40
---
-- 定义参数
-- 1.优惠卷id
local voucherId = ARGV[1]
--2.用户id
local userId = ARGV[2]

-- key
local stockKey = 'seckill:stock:'..voucherId  -- 库存key
local orderKey = 'seckill:order:'..voucherId  -- 订单key

if(tonumber(redis.call('get',stockKey)) <= 0) then -- 这个get返回的是字符串类型，所以要tonumber转成数字
    return 1 -- 库存不足返回1
end

if(redis.call('sismember',orderKey,userId) == 1) then
    return 2 -- 已下单返回2
end

redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
return 0 -- 又购买资格返回0

